/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as BarberoRouteImport } from './routes/barbero'
import { Route as AdministracionRouteImport } from './routes/administracion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as BarberoIndexRouteImport } from './routes/barbero.index'
import { Route as AdministracionIndexRouteImport } from './routes/administracion.index'
import { Route as ClienteSettingsRouteImport } from './routes/cliente.settings'
import { Route as ClienteLoyaltyRouteImport } from './routes/cliente.loyalty'
import { Route as ClienteHistoryRouteImport } from './routes/cliente.history'
import { Route as ClienteBookRouteImport } from './routes/cliente.book'
import { Route as BarberoSettingsRouteImport } from './routes/barbero.settings'
import { Route as BarberoScheduleRouteImport } from './routes/barbero.schedule'
import { Route as BarberoEarningsRouteImport } from './routes/barbero.earnings'
import { Route as BarberoClientsRouteImport } from './routes/barbero.clients'
import { Route as AdministracionStatisticsRouteImport } from './routes/administracion.statistics'
import { Route as AdministracionSettingsRouteImport } from './routes/administracion.settings'
import { Route as AdministracionInventoryRouteImport } from './routes/administracion.inventory'
import { Route as AdministracionEarningsRouteImport } from './routes/administracion.earnings'
import { Route as AdministracionClientsRouteImport } from './routes/administracion.clients'
import { Route as AdministracionBarbersRouteImport } from './routes/administracion.barbers'
import { Route as AdministracionAppointmentsRouteImport } from './routes/administracion.appointments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberoRoute = BarberoRouteImport.update({
  id: '/barbero',
  path: '/barbero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRoute = AdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const BarberoIndexRoute = BarberoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BarberoRoute,
} as any)
const AdministracionIndexRoute = AdministracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministracionRoute,
} as any)
const ClienteSettingsRoute = ClienteSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteLoyaltyRoute = ClienteLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteHistoryRoute = ClienteHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteBookRoute = ClienteBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ClienteRoute,
} as any)
const BarberoSettingsRoute = BarberoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BarberoRoute,
} as any)
const BarberoScheduleRoute = BarberoScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => BarberoRoute,
} as any)
const BarberoEarningsRoute = BarberoEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => BarberoRoute,
} as any)
const BarberoClientsRoute = BarberoClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BarberoRoute,
} as any)
const AdministracionStatisticsRoute =
  AdministracionStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AdministracionRoute,
  } as any)
const AdministracionSettingsRoute = AdministracionSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdministracionRoute,
} as any)
const AdministracionInventoryRoute = AdministracionInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdministracionRoute,
} as any)
const AdministracionEarningsRoute = AdministracionEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AdministracionRoute,
} as any)
const AdministracionClientsRoute = AdministracionClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdministracionRoute,
} as any)
const AdministracionBarbersRoute = AdministracionBarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => AdministracionRoute,
} as any)
const AdministracionAppointmentsRoute =
  AdministracionAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AdministracionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/barbero': typeof BarberoRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/administracion/appointments': typeof AdministracionAppointmentsRoute
  '/administracion/barbers': typeof AdministracionBarbersRoute
  '/administracion/clients': typeof AdministracionClientsRoute
  '/administracion/earnings': typeof AdministracionEarningsRoute
  '/administracion/inventory': typeof AdministracionInventoryRoute
  '/administracion/settings': typeof AdministracionSettingsRoute
  '/administracion/statistics': typeof AdministracionStatisticsRoute
  '/barbero/clients': typeof BarberoClientsRoute
  '/barbero/earnings': typeof BarberoEarningsRoute
  '/barbero/schedule': typeof BarberoScheduleRoute
  '/barbero/settings': typeof BarberoSettingsRoute
  '/cliente/book': typeof ClienteBookRoute
  '/cliente/history': typeof ClienteHistoryRoute
  '/cliente/loyalty': typeof ClienteLoyaltyRoute
  '/cliente/settings': typeof ClienteSettingsRoute
  '/administracion/': typeof AdministracionIndexRoute
  '/barbero/': typeof BarberoIndexRoute
  '/cliente/': typeof ClienteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administracion/appointments': typeof AdministracionAppointmentsRoute
  '/administracion/barbers': typeof AdministracionBarbersRoute
  '/administracion/clients': typeof AdministracionClientsRoute
  '/administracion/earnings': typeof AdministracionEarningsRoute
  '/administracion/inventory': typeof AdministracionInventoryRoute
  '/administracion/settings': typeof AdministracionSettingsRoute
  '/administracion/statistics': typeof AdministracionStatisticsRoute
  '/barbero/clients': typeof BarberoClientsRoute
  '/barbero/earnings': typeof BarberoEarningsRoute
  '/barbero/schedule': typeof BarberoScheduleRoute
  '/barbero/settings': typeof BarberoSettingsRoute
  '/cliente/book': typeof ClienteBookRoute
  '/cliente/history': typeof ClienteHistoryRoute
  '/cliente/loyalty': typeof ClienteLoyaltyRoute
  '/cliente/settings': typeof ClienteSettingsRoute
  '/administracion': typeof AdministracionIndexRoute
  '/barbero': typeof BarberoIndexRoute
  '/cliente': typeof ClienteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/barbero': typeof BarberoRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/login': typeof LoginRoute
  '/administracion/appointments': typeof AdministracionAppointmentsRoute
  '/administracion/barbers': typeof AdministracionBarbersRoute
  '/administracion/clients': typeof AdministracionClientsRoute
  '/administracion/earnings': typeof AdministracionEarningsRoute
  '/administracion/inventory': typeof AdministracionInventoryRoute
  '/administracion/settings': typeof AdministracionSettingsRoute
  '/administracion/statistics': typeof AdministracionStatisticsRoute
  '/barbero/clients': typeof BarberoClientsRoute
  '/barbero/earnings': typeof BarberoEarningsRoute
  '/barbero/schedule': typeof BarberoScheduleRoute
  '/barbero/settings': typeof BarberoSettingsRoute
  '/cliente/book': typeof ClienteBookRoute
  '/cliente/history': typeof ClienteHistoryRoute
  '/cliente/loyalty': typeof ClienteLoyaltyRoute
  '/cliente/settings': typeof ClienteSettingsRoute
  '/administracion/': typeof AdministracionIndexRoute
  '/barbero/': typeof BarberoIndexRoute
  '/cliente/': typeof ClienteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/barbero'
    | '/cliente'
    | '/login'
    | '/administracion/appointments'
    | '/administracion/barbers'
    | '/administracion/clients'
    | '/administracion/earnings'
    | '/administracion/inventory'
    | '/administracion/settings'
    | '/administracion/statistics'
    | '/barbero/clients'
    | '/barbero/earnings'
    | '/barbero/schedule'
    | '/barbero/settings'
    | '/cliente/book'
    | '/cliente/history'
    | '/cliente/loyalty'
    | '/cliente/settings'
    | '/administracion/'
    | '/barbero/'
    | '/cliente/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/administracion/appointments'
    | '/administracion/barbers'
    | '/administracion/clients'
    | '/administracion/earnings'
    | '/administracion/inventory'
    | '/administracion/settings'
    | '/administracion/statistics'
    | '/barbero/clients'
    | '/barbero/earnings'
    | '/barbero/schedule'
    | '/barbero/settings'
    | '/cliente/book'
    | '/cliente/history'
    | '/cliente/loyalty'
    | '/cliente/settings'
    | '/administracion'
    | '/barbero'
    | '/cliente'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/barbero'
    | '/cliente'
    | '/login'
    | '/administracion/appointments'
    | '/administracion/barbers'
    | '/administracion/clients'
    | '/administracion/earnings'
    | '/administracion/inventory'
    | '/administracion/settings'
    | '/administracion/statistics'
    | '/barbero/clients'
    | '/barbero/earnings'
    | '/barbero/schedule'
    | '/barbero/settings'
    | '/cliente/book'
    | '/cliente/history'
    | '/cliente/loyalty'
    | '/cliente/settings'
    | '/administracion/'
    | '/barbero/'
    | '/cliente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracionRoute: typeof AdministracionRouteWithChildren
  BarberoRoute: typeof BarberoRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbero': {
      id: '/barbero'
      path: '/barbero'
      fullPath: '/barbero'
      preLoaderRoute: typeof BarberoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/barbero/': {
      id: '/barbero/'
      path: '/'
      fullPath: '/barbero/'
      preLoaderRoute: typeof BarberoIndexRouteImport
      parentRoute: typeof BarberoRoute
    }
    '/administracion/': {
      id: '/administracion/'
      path: '/'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AdministracionIndexRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/cliente/settings': {
      id: '/cliente/settings'
      path: '/settings'
      fullPath: '/cliente/settings'
      preLoaderRoute: typeof ClienteSettingsRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/loyalty': {
      id: '/cliente/loyalty'
      path: '/loyalty'
      fullPath: '/cliente/loyalty'
      preLoaderRoute: typeof ClienteLoyaltyRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/history': {
      id: '/cliente/history'
      path: '/history'
      fullPath: '/cliente/history'
      preLoaderRoute: typeof ClienteHistoryRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/book': {
      id: '/cliente/book'
      path: '/book'
      fullPath: '/cliente/book'
      preLoaderRoute: typeof ClienteBookRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/barbero/settings': {
      id: '/barbero/settings'
      path: '/settings'
      fullPath: '/barbero/settings'
      preLoaderRoute: typeof BarberoSettingsRouteImport
      parentRoute: typeof BarberoRoute
    }
    '/barbero/schedule': {
      id: '/barbero/schedule'
      path: '/schedule'
      fullPath: '/barbero/schedule'
      preLoaderRoute: typeof BarberoScheduleRouteImport
      parentRoute: typeof BarberoRoute
    }
    '/barbero/earnings': {
      id: '/barbero/earnings'
      path: '/earnings'
      fullPath: '/barbero/earnings'
      preLoaderRoute: typeof BarberoEarningsRouteImport
      parentRoute: typeof BarberoRoute
    }
    '/barbero/clients': {
      id: '/barbero/clients'
      path: '/clients'
      fullPath: '/barbero/clients'
      preLoaderRoute: typeof BarberoClientsRouteImport
      parentRoute: typeof BarberoRoute
    }
    '/administracion/statistics': {
      id: '/administracion/statistics'
      path: '/statistics'
      fullPath: '/administracion/statistics'
      preLoaderRoute: typeof AdministracionStatisticsRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/settings': {
      id: '/administracion/settings'
      path: '/settings'
      fullPath: '/administracion/settings'
      preLoaderRoute: typeof AdministracionSettingsRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/inventory': {
      id: '/administracion/inventory'
      path: '/inventory'
      fullPath: '/administracion/inventory'
      preLoaderRoute: typeof AdministracionInventoryRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/earnings': {
      id: '/administracion/earnings'
      path: '/earnings'
      fullPath: '/administracion/earnings'
      preLoaderRoute: typeof AdministracionEarningsRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/clients': {
      id: '/administracion/clients'
      path: '/clients'
      fullPath: '/administracion/clients'
      preLoaderRoute: typeof AdministracionClientsRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/barbers': {
      id: '/administracion/barbers'
      path: '/barbers'
      fullPath: '/administracion/barbers'
      preLoaderRoute: typeof AdministracionBarbersRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/appointments': {
      id: '/administracion/appointments'
      path: '/appointments'
      fullPath: '/administracion/appointments'
      preLoaderRoute: typeof AdministracionAppointmentsRouteImport
      parentRoute: typeof AdministracionRoute
    }
  }
}

interface AdministracionRouteChildren {
  AdministracionAppointmentsRoute: typeof AdministracionAppointmentsRoute
  AdministracionBarbersRoute: typeof AdministracionBarbersRoute
  AdministracionClientsRoute: typeof AdministracionClientsRoute
  AdministracionEarningsRoute: typeof AdministracionEarningsRoute
  AdministracionInventoryRoute: typeof AdministracionInventoryRoute
  AdministracionSettingsRoute: typeof AdministracionSettingsRoute
  AdministracionStatisticsRoute: typeof AdministracionStatisticsRoute
  AdministracionIndexRoute: typeof AdministracionIndexRoute
}

const AdministracionRouteChildren: AdministracionRouteChildren = {
  AdministracionAppointmentsRoute: AdministracionAppointmentsRoute,
  AdministracionBarbersRoute: AdministracionBarbersRoute,
  AdministracionClientsRoute: AdministracionClientsRoute,
  AdministracionEarningsRoute: AdministracionEarningsRoute,
  AdministracionInventoryRoute: AdministracionInventoryRoute,
  AdministracionSettingsRoute: AdministracionSettingsRoute,
  AdministracionStatisticsRoute: AdministracionStatisticsRoute,
  AdministracionIndexRoute: AdministracionIndexRoute,
}

const AdministracionRouteWithChildren = AdministracionRoute._addFileChildren(
  AdministracionRouteChildren,
)

interface BarberoRouteChildren {
  BarberoClientsRoute: typeof BarberoClientsRoute
  BarberoEarningsRoute: typeof BarberoEarningsRoute
  BarberoScheduleRoute: typeof BarberoScheduleRoute
  BarberoSettingsRoute: typeof BarberoSettingsRoute
  BarberoIndexRoute: typeof BarberoIndexRoute
}

const BarberoRouteChildren: BarberoRouteChildren = {
  BarberoClientsRoute: BarberoClientsRoute,
  BarberoEarningsRoute: BarberoEarningsRoute,
  BarberoScheduleRoute: BarberoScheduleRoute,
  BarberoSettingsRoute: BarberoSettingsRoute,
  BarberoIndexRoute: BarberoIndexRoute,
}

const BarberoRouteWithChildren =
  BarberoRoute._addFileChildren(BarberoRouteChildren)

interface ClienteRouteChildren {
  ClienteBookRoute: typeof ClienteBookRoute
  ClienteHistoryRoute: typeof ClienteHistoryRoute
  ClienteLoyaltyRoute: typeof ClienteLoyaltyRoute
  ClienteSettingsRoute: typeof ClienteSettingsRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteBookRoute: ClienteBookRoute,
  ClienteHistoryRoute: ClienteHistoryRoute,
  ClienteLoyaltyRoute: ClienteLoyaltyRoute,
  ClienteSettingsRoute: ClienteSettingsRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracionRoute: AdministracionRouteWithChildren,
  BarberoRoute: BarberoRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
